# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
flake.nixosModules.laptop = {
 config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-eac468a1-2ebe-4a76-b6fb-21841394da84";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-eac468a1-2ebe-4a76-b6fb-21841394da84".device = "/dev/disk/by-uuid/eac468a1-2ebe-4a76-b6fb-21841394da84";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6F98-C7E5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c2ab4dbf-e8a9-4456-bf34-9901d9f90a95"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}
